name: solarsparkar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  fluttertoast: ^8.2.10
  curved_navigation_bar: ^1.0.6
  youtube_player_flutter: ^9.1.1
  # ar_flutter_plugin: ^0.7.3
  # ar_flutter_plugin_updated: ^0.0.1
  # ar_flutter_plugin_flutterflow: ^0.7.55
  arkit_plugin: ^1.1.1
  # arcore_flutter_plugin: ^0.1.0
  vector_math: ^2.1.4
  collection: ^1.19.0
  carousel_slider: ^5.0.0
  flutter_tts: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/3dmodels/glb/
    - assets/planet_png/
    - assets/scene/

  fonts:
    - family: Sniglet
      fonts:
        - asset: assets/fonts/Sniglet-Regular.ttf
